---
name: Monica Personal CRM
version: 0.0.4
slug: monica_crm
description: An open source personal CRM - Monica helps you organize the social interactions with your loved ones.
url: https://github.com/mww/hassio-addons
services:
  - mysql:need
arch:
  - aarch64
  - amd64
init: false
ports:
  443/tcp: 8443
ports_description:
  443/tcp: Secure web interface
map:
  - share:rw
  - ssl
options:
  app_url: https://localhost
  certfile: fullchain.pem
  keyfile: privkey.pem
  server_name: localhost
  server_admin: admin@example.com
  mail_host: smtp.gmail.com
  mail_port: 587
  mail_encryption: tls
  mail_username: example@gmail.com
  mail_password: password
  mail_from_address: example@gmail.com
  mail_from_name: monica
  trusted_proxies:
  enable_access_logs: false
  dev_server: false
schema:
  app_url: str
  certfile: str
  keyfile: str
  server_name: str
  server_admin: str
  mail_host: str
  mail_port: port
  mail_encryption: str
  mail_username: email
  mail_password: password
  mail_from_address: email
  mail_from_name: str
  trusted_proxies: str
  enable_access_logs: bool
  dev_server: bool
