---
name: InfluxDB2
version: 0.0.3
slug: influxdb2
description: Scalable datastore for metrics, events, and real-time analytics
url: https://github.com/hassio-addons/addon-influxdb
panel_icon: mdi:chart-areaspline
startup: services
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
  - ssl
ports:
  80/tcp: null
  8086/tcp: 8086
ports_description:
  80/tcp: Web interface (Not required for Ingress)
  8086/tcp: InfluxDB server
options:
  certfile: fullchain.pem
  keyfile: privkey.pem
  envvars: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  certfile: str
  keyfile: str
  envvars:
    - name: match(^INFLUXD_([A-Z0-9_])+$)
      value: str
